[package]
name = "host-demo"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[features]
default = []
wasm3 = ["runtime/engine-wasm3"]

[dependencies]
runtime = { path = "../runtime" }
